//MainApp
export const OPEN_APPBAR = 'OPEN_APPBAR';
export const OPEN_LOGIN = 'OPEN_LOGIN';
export const CHANGE_CONTENT = 'CHANGE_CONTENT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

//QuickQuoteApp
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const GET_QUOTE = 'GET_QUOTE';
export const UPDATE_STOCK_INFO = 'UPDATE_STOCK_INFO';
export const ADD_MYFAVORITES_STOCK = 'ADD_MYFAVORITES_STOCK';
export const DEL_MYFAVORITES_STOCK = 'DEL_MYFAVORITES_STOCK';
export const UPDATE_MYFAVORITES_STOCK = 'UPDATE_MYFAVORITES_STOCK';
export const REFRESH_STOCK_PRICE = 'REFRESH_STOCK_PRICE';
export const GET_MYFAVORITES_STOCK = 'GET_MYFAVORITES_STOCK';
